### ISSUE TITLE
does not work with python 3.10

### ISSUE THREAD

**Issue by samirsd** [jazzband/django-push-notifications#675]

**Comment by uzza1hossain** [comment]
Can you provide additional context?

**Comment by samirsd** [comment]
when I try to send a push notification I get  `cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

**Comment by samirsd** [comment]
others have commented on this issue. it seems to be related to unmaintained dependencies, specifically `apns2` and `hyper` I believe.

https://github.com/jazzband/django-push-notifications/issues/583

https://github.com/jazzband/django-push-notifications/issues/622#issuecomment-1331050728

**Comment by samirsd** [comment]
yes i’ve been using aiopns as a result of these issues actually and it has been working for me

**Comment by bradleydworak** [comment]
That’s great feedback, thank you. I’m tempted to open another Issue and
propose to the group to switch to aioapns and drop apns2 if they aren’t
jumping on supporting python 10 by this point in time.

**Comment by bradleydworak** [comment]
@samirsd Did you encounter an issue with aioapns complaining that it is expecting an EllipticCurve PrivateKey/PublicKey pair? If so, could you tell me what you did to resolve the issue, or point me to a online reference? I have the APNS cert/key pem file already.

**Comment by samirsd** [comment]
@bradleydworak I didn't encounter that issue but I've been using it in sandbox mode

Maybe double check the steps for generating your `.p8` file? 

my code looks like this:

`async def send_message(device_token, message):
    key_path =  os.path.join(settings.BASE_DIR, "path/to/my/AuthKey_12345ABC.p8")
    use_sandbox = True

    apns_key_client = APNs(
        key= key_path,
        key_id=KEY_ID,
        team_id=TEAM_ID,
        topic=IOS_APP_BUNDLE_ID,  # Bundle ID
        use_sandbox=use_sandbox,
    )
    request = NotificationRequest(
        device_token=device_token,
        message = {
            "aps": {
                "alert": message,
                "badge": "1",
            }
        },
        notification_id=str(uuid4()),  # optional
        time_to_live=3,                # optional
        push_type=PushType.ALERT,      # optional             # optional
    )
    await apns_key_client.send_notification(request)
`

I did however encounter an issue where `aioapns` would send repeated push notifications so I just commented out the retry logic as follows: https://github.com/samirsd/aioapns/commit/f7e6081da214b426930a8a5bf8fe25a2f4433f52

**Comment by bradleydworak** [comment]
Thx for the feedback. Yes I wasn’t able to find any documentation on
generating the .p8 file, and unclear if it is derived from the APNS
cert/key or generated separately. Do you have a link to instructions and/or
sample code on how to do this? I’m hoping to add some documentation to the
aioapns Readme once I understand this better.

**Comment by samirsd** [comment]
It has to be done from the apple developer website https://stackoverflow.com/questions/44631803/ios-swift-how-to-create-p8-file

**Comment by bradleydworak** [comment]
Thx…finally got it working. Without any documentation it wasn’t clear that
you use either the key or the cert file but not both. I’m hoping to make a
pull request and forgo apns.

**Comment by samirsd** [comment]
no prob glad i could help

**Comment by AsimDawrat** [comment]
Any fork you know which uses aioapns?
